require("raphmt.set")
require("raphmt.keybind")
require("raphmt.plugins")

--  plugins
require("raphmt.plugins.theme")
require("raphmt.plugins.treesitter")
require("raphmt.plugins.telescope")
require("raphmt.plugins.lualine")
require("raphmt.plugins.autopairs")
require("raphmt.plugins.harpoon")
require("raphmt.plugins.lsp")
require("raphmt.plugins.conform")
require("raphmt.plugins.comment")
require("raphmt.plugins.surrounds")
require("raphmt.plugins.gitsigns")
require("raphmt.plugins.startup")
