require("raphmt.set")
require("raphmt.keybind")
require("raphmt.plugins")

--  plugins
require("raphmt.plugins.aerial")
require("raphmt.plugins.autopairs")
require("raphmt.plugins.bufferline")
require("raphmt.plugins.comment")
require("raphmt.plugins.conform")
require("raphmt.plugins.gitsigns")
require("raphmt.plugins.harpoon")
require("raphmt.plugins.leap")
-- require("raphmt.plugins.lsp")
require("raphmt.plugins.lualine")
require("raphmt.plugins.smartsplits")
require("raphmt.plugins.treesitter")
require("raphmt.plugins.surrounds")
require("raphmt.plugins.tabline")
require("raphmt.plugins.telescope")
require("raphmt.plugins.catppuccin")
require("raphmt.plugins.illuminate")
